Remove previous ECR images

diff --git a/.github/workflows/ecr.yml b/.github/workflows/ecr.yml
--- a/.github/workflows/ecr.yml
+++ b/.github/workflows/ecr.yml
@@ -37,23 +37,40 @@ jobs:
         run: |
           cd ECR/app
           SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
-          IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:ping_pong-${SHORT_SHA}"
-          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest --push .
+          IMAGE_NAME="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$SHORT_SHA"
+          echo "Building image with tags: ${IMAGE_NAME} and latest"
+          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE_NAME -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$SHORT_SHA --push .
+
+      - name: Debug Image Name
+        run: |
+          echo "SHORT_SHA=${SHORT_SHA}"
+          echo "IMAGE_NAME=${IMAGE_NAME}"
 
       - name: Pull and run Docker image for testing
         env:
           ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
-          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
-          docker run -d -p 8080:8080 --name test-container ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest
+          docker pull "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${SHORT_SHA}"
+          docker run -d -p 8080:8080 --name test-container "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"
           sleep 10 # Increase sleep duration to give the container more time to start
           docker logs test-container # Check container logs for debugging
-          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ping | grep -q "200" && echo "Test Passed!" || echo "Test Failed!"
+          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ping | grep -q "200" && echo "Test Passed!" || { echo "Test Failed!"; exit 1; }
           docker stop test-container
           docker rm test-container
+
+      - name: Remove previous ECR images
+        if: success()
+        env:
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+        run: |
+          aws ecr list-images --repository-name $ECR_REPOSITORY --filter "tagStatus=TAGGED" --query 'imageIds[?imageTag!=`latest`]' --output json | \
+          jq -c '.[]' | \
+          xargs -I {} aws ecr batch-delete-image --repository-name $ECR_REPOSITORY --image-ids {}
 
       - name: Post-deployment steps (optional)
         run: |
           SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
-          echo "Docker images have been successfully pushed to ECR with tags ping_pong-${SHORT_SHA} and latest."
+          echo "Docker images have been successfully pushed to ECR with tags ${SHORT_SHA} and latest."
+
